export { default as AboutUs } from './aboutUs/AboutUs'
export { default as Bookmark } from './bookmark/Bookmark'
export { default as Carts } from './cart/Carts'
export { default as Contacts } from './contacts/Contacts'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as SubHeader } from './subHeader/SubHeader'
export { default as Login } from './login/Login'
export { default as Nav } from './nav/Nav'
export { default as Loader } from './payloader/Loader'
export { default as Pagination } from './paginator/Pagination'
export { default as Product } from './product/Product'
export { default as Products } from './products/Products'
export { default as SignUp } from './signup/SignUp'
export { default as Scleton } from './scleton/Scleton'
// export * from './notFaund/NotFound'
